/* redux > actions > actionType */
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_LOADING = 'FETCH_POST_LOADING';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_LOADING = 'ADD_POST_LOADING';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

export const FETCH_REPLY = 'FETCH_REPLY';
export const FETCH_REPLY_ERROR = 'FETCH_REPLY_ERROR';
export const FETCH_REPLY_SUCCESS = 'FETCH_REPLY_SUCCESS';
export const FETCH_REPLY_LOADING = 'FETCH_REPLY_LOADING';
export const ADD_REPLY = 'ADD_REPLY';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_LOADING = 'ADD_REPLY_LOADING';
export const ADD_REPLY_ERROR = 'ADD_REPLY_ERROR';
